# Generated by Django 4.2 on 2023-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
    ]
