# Generated by Django 4.2 on 2024-07-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_offer_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
